# Generated by Django 3.1.12 on 2021-06-08 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20210608_1847'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuestionCategory',
            new_name='QuestionList',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question_category',
            new_name='question_list',
        ),
    ]
