# Generated by Django 3.1.12 on 2021-06-08 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_auto_20210608_2009'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionlist',
            options={},
        ),
    ]
